//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionBlanco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPORALIDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEMPORALIDAD()
        {
            this.GRAFICO = new HashSet<GRAFICO>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string auxiliar { get; set; }
        public string fecha_inicio { get; set; }

        public string _fecha_inicio
        {
            get
            {
                if (fecha_inicio.Contains("/"))
                {
                    return fecha_inicio;
                }
                DateTime conv = DateTime.FromOADate(Int32.Parse(fecha_inicio));
                return conv.ToShortDateString();
            }

            set { fecha_inicio = value; }
        }
        public string fecha_termino { get; set; }
        public string _fecha_termino
        {
            get
            {
                if (fecha_termino.Contains("/"))
                {
                    return fecha_termino;
                }
                DateTime conv = DateTime.FromOADate(Int32.Parse(fecha_termino));
                return conv.ToShortDateString();
            }

            set { fecha_inicio = value; }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRAFICO> GRAFICO { get; set; }
    }
}
